import { z } from "zod";

/**
 *  LOG  {
  "success": true,
  "caremanagers": [
    {
      "id": 6,
      "email": "hammes.lucas@example.net",
      "email_verified_at": null,
      "created_at": "2025-05-25T06:57:33.000000Z",
      "updated_at": "2025-05-30T07:44:44.000000Z",
      "first_name": "Demetrius",
      "last_name": "Becker",
      "birthday": "1993-02-22T16:00:00.000000Z",
      "civil_status": "Single",
      "educational_background": "Graduate",
      "mobile": "+639039437985",
      "landline": "92143122",
      "personal_email": "cormier.jerome@example.org",
      "address": "849 Gleichner Field\nOwenborough, DC 01320",
      "gender": "Female",
      "religion": "Other",
      "nationality": "Filipino",
      "volunteer_status": "Active",
      "status_start_date": "2025-05-24T16:00:00.000000Z",
      "status_end_date": "2026-05-24T16:00:00.000000Z",
      "role_id": 2,
      "status": "Inactive",
      "organization_role_id": null,
      "assigned_municipality_id": 2,
      "assigned_care_manager_id": null,
      "photo": null,
      "government_issued_id": null,
      "sss_id_number": "3963890345",
      "philhealth_id_number": "1457260506",
      "pagibig_id_number": "1327581850",
      "cv_resume": null,
      "updated_by": 1,
      "municipality": {
        "municipality_id": 2,
        "municipality_name": "San Roque",
        "province_id": 1,
        "created_at": "2025-05-25T06:49:11.000000Z",
        "updated_at": "2025-05-25T06:49:11.000000Z"
      },
      "photo_url": null,
      "government_issued_id_url": null,
      "cv_resume_url": null
    },
    {
      "id": 5,
      "email": "brown.eva@example.com",
      "email_verified_at": null,
      "created_at": "2025-05-25T06:57:33.000000Z",
      "updated_at": "2025-05-30T07:45:15.000000Z",
      "first_name": "Lilyan",
      "last_name": "Sauer",
      "birthday": "2005-10-31T16:00:00.000000Z",
      "civil_status": "Widowed",
      "educational_background": "College",
      "mobile": "+636351288781",
      "landline": "81536073",
      "personal_email": "favian.oreilly@example.com",
      "address": "45920 Jalon Greens Suite 209\r\nWalshville, NV 68408-0449",
      "gender": "Female",
      "religion": "Muslim",
      "nationality": "Filipino",
      "volunteer_status": "Active",
      "status_start_date": "2025-05-24T16:00:00.000000Z",
      "status_end_date": "2026-05-24T16:00:00.000000Z",
      "role_id": 2,
      "status": "Active",
      "organization_role_id": null,
      "assigned_municipality_id": 1,
      "assigned_care_manager_id": null,
      "photo": null,
      "government_issued_id": null,
      "sss_id_number": "3532771530",
      "philhealth_id_number": "1285830472",
      "pagibig_id_number": "3549216437",
      "cv_resume": null,
      "updated_by": 1,
      "municipality": {
        "municipality_id": 1,
        "municipality_name": "Mondragon",
        "province_id": 1,
        "created_at": "2025-05-25T06:49:11.000000Z",
        "updated_at": "2025-05-25T06:49:11.000000Z"
      },
      "photo_url": null,
      "government_issued_id_url": null,
      "cv_resume_url": null
    }
  ]
}
 */

export const careManagerSchema = z.object({
    id: z.number(),
    email: z.string().email(),
    email_verified_at: z.string().nullable(),
    created_at: z.string(),
    updated_at: z.string(),
    first_name: z.string(),
    last_name: z.string(),
    birthday: z.string(),
    civil_status: z.string(),
    educational_background: z.string(),
    mobile: z.string(),
    landline: z.string(),
    personal_email: z.string().email(),
    address: z.string(),
    gender: z.string(),
    religion: z.string(),
    nationality: z.string(),
    volunteer_status: z.string(),
    status_start_date: z.string(),
    status_end_date: z.string(),
    role_id: z.number(),
    status: z.enum(["Active", "Inactive"]),
    organization_role_id: z.number().nullable(),
    assigned_municipality_id: z.number(),
    assigned_care_manager_id: z.number().nullable(),
    photo: z.string().nullable(),
    government_issued_id: z.string().nullable(),
    sss_id_number: z.string(),
    philhealth_id_number: z.string(),
    pagibig_id_number: z.string(),
    cv_resume: z.string().nullable(),
    updated_by: z.number(),
    municipality: z.object({
        municipality_id: z.number(),
        municipality_name: z.string(),
        province_id: z.number(),
        created_at: z.string(),
        updated_at: z.string(),
    }),
    photo_url: z.string().nullable(),
    government_issued_id_url: z.string().nullable(),
    cv_resume_url: z.string().nullable(),
});
