import { z } from "zod";

export const careWorkerSchema = z.object({
    id: z.number(),
    email: z.string().email(),
    email_verified_at: z.string().nullable(),
    created_at: z.string(),
    updated_at: z.string(),
    first_name: z.string(),
    last_name: z.string(),
    birthday: z.string(),
    civil_status: z.string(),
    educational_background: z.string(),
    mobile: z.string(),
    landline: z.string(),
    personal_email: z.string().email(),
    address: z.string(),
    gender: z.string(),
    religion: z.string(),
    nationality: z.string(),
    volunteer_status: z.string(),
    status_start_date: z.string(),
    status_end_date: z.string(),
    role_id: z.number(),
    status: z.enum(["Active", "Inactive"]),
    organization_role_id: z.number().nullable(),
    assigned_municipality_id: z.number(),
    assigned_care_manager_id: z.number(),
    photo: z.string().nullable(),
    government_issued_id: z.string().nullable(),
    sss_id_number: z.string(),
    philhealth_id_number: z.string(),
    pagibig_id_number: z.string(),
    cv_resume: z.string().nullable(),
    updated_by: z.number(),
    municipality: z.object({
        municipality_id: z.number(),
        municipality_name: z.string(),
        province_id: z.number(),
        created_at: z.string(),
        updated_at: z.string(),
    }),
    photo_url: z.string().nullable(),
    government_issued_id_url: z.string().nullable(),
    cv_resume_url: z.string().nullable(),
})
