name: EAS Build (Android Preview)

on:
    workflow_dispatch:
    push:
        branches:
            - test
        paths:
            - 'mobile/**'

jobs:
    update:
        runs-on: ubuntu-latest
        env:
            DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
            API_URL: https://discord.com/api/v10/channels
            DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_PIPELINE_CHANNEL_ID }}

        steps:
            - name: Notify Discord – Build Started
              if: always()
              run: |
                  RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  curl -X POST "$API_URL/$DISCORD_CHANNEL_ID/messages" \
                    -H "Authorization: Bot $DISCORD_BOT_TOKEN" \
                    -H "Content-Type: application/json" \
                    -d "{\"content\":\"🚀 Android build started for **${{ github.repository }}** (#${{ github.run_number }})\"}"

            - name: 🏗 Setup repo
              uses: actions/checkout@v3

            - name: 🏗 Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: yarn

            - name: 🏗 Setup EAS
              uses: expo/expo-github-action@v8
              with:
                  eas-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}

            - name: 📦 Install dependencies
              run: npm install

            - name: 🏗 Build Android Preview
              run: eas build --platform android --local --profile preview

            - name: Notify Discord – Build Succeeded
              if: success()
              run: |
                  curl -X POST "$API_URL/$DISCORD_CHANNEL_ID/messages" \
                    -H "Authorization: Bot $DISCORD_BOT_TOKEN" \
                    -H "Content-Type: application/json" \
                    -d "{\"content\":\"✅ Android build succeeded for **${{ github.repository }}** (#${{ github.run_number }})\"}"

            - name: Notify Discord – Build Failed
              if: failure()
              run: |
                  curl -X POST "$API_URL/$DISCORD_CHANNEL_ID/messages" \
                    -H "Authorization: Bot $DISCORD_BOT_TOKEN" \
                    -H "Content-Type: application/json" \
                    -d "{\"content\":\"❌ Android build failed for **${{ github.repository }}** (#${{ github.run_number }})\"}"