name: Deploy Test Environment

on:
  workflow_dispatch:
  push:
    branches:
      - test
    paths:
      - 'web/**'

env:
  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
  API_URL: https://discord.com/api/v10/channels

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    env:
      DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_PIPELINE_CHANNEL_ID }}
    steps:
      - name: Notify Discord – Run Started
        if: always()
        run: |
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}}"
          curl -X POST "$API_URL/$DISCORD_CHANNEL_ID/messages" \
            -H "Authorization: Bot $DISCORD_BOT_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"content\":\"🚀 Workflow started for **${{ github.repository }}** (#${{ github.run_number }})\n<$RUN_URL>\"}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DOCR
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCR_REGISTRY }}
          username: ${{ secrets.DOCR_USERNAME }}
          password: ${{ secrets.DOCR_TOKEN }}

      - name: Build and push Docker image
        run: |
          REGISTRY=${{ vars.DOCR_REGISTRY }}
          IMAGE="$REGISTRY/sulong-kalinga-web:${{ github.sha }}"
          docker build -f web/docker/Dockerfile -t "$IMAGE" web
          docker push "$IMAGE"

      - name: Notify Discord – Build Succeeded
        if: success()
        run: |
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}}"
          curl -X POST "$API_URL/$DISCORD_CHANNEL_ID/messages" \
            -H "Authorization: Bot $DISCORD_BOT_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"content\":\"✅ Build succeeded for **${{ github.repository }}** (#${{ github.run_number }})\n<$RUN_URL>\"}"

      - name: Notify Discord – Build Failed
        if: failure()
        run: |
          LOGS_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/logs}}"
          curl -X POST "$API_URL/$DISCORD_CHANNEL_ID/messages" \
            -H "Authorization: Bot $DISCORD_BOT_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"content\":\"❌ Build **failed** for **${{ github.repository }}** (#${{ github.run_number }})\nSee logs: <$LOGS_URL>\"}"

  deploy:
    environment: test
    needs: build
    runs-on: ubuntu-latest
    env:
      DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_PIPELINE_CHANNEL_ID }}
    steps:
      - name: Notify Discord – Deploy Started
        if: always()
        run: |
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}}"
          curl -X POST "$API_URL/$DISCORD_CHANNEL_ID/messages" \
            -H "Authorization: Bot $DISCORD_BOT_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"content\":\"🚀 Deploy started for **${{ github.repository }}** (#${{ github.run_number }})\n<$RUN_URL>\"}"

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Run server setup script
        run: |
          sshpass -p "${{ secrets.CONTAINER_PASSWORD }}" ssh \
            -o StrictHostKeyChecking=no \
            -o ServerAliveInterval=30 \
            -o ServerAliveCountMax=5 \
            root@${{ vars.DEPLOY_HOST }} <<'EOF'
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-get update -y
            sudo apt-get install --no-install-recommends -y docker.io
          EOF

      - name: Parse .env secret into Docker env args
        shell: bash
        env:
          ENVARS: ${{ secrets.ENVARS }}
        run: |
          echo "$ENVARS" > .env
          ENV_ARGS=$(grep -v '^\s*#' .env \
                     | grep -v '^\s*$' \
                     | awk -F= '{printf "-e %s=\"%s\" ", $1, $2}')
          echo "ENV_ARGS=$ENV_ARGS" >> $GITHUB_ENV
          rm .env

      - name: Deploy to Droplet via password
        run: |
          IMAGE=${{ vars.DOCR_REGISTRY }}/sulong-kalinga-web:${{ github.sha }}
          sshpass -p "${{ secrets.CONTAINER_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ vars.DEPLOY_HOST }} <<EOF
            echo "${{ secrets.DOCR_TOKEN }}" | docker login ${{ vars.DOCR_REGISTRY }} \
              --username ${{ secrets.DOCR_USERNAME }} --password-stdin
            docker pull $IMAGE
            docker stop sulong-kalinga || true
            docker rm sulong-kalinga || true
            docker run -d --name sulong-kalinga -p 80:8000 \
              $ENV_ARGS -e ENVIRONMENT="${{ github.ref_name }}" $IMAGE
            docker container prune -f
            docker image prune -f
            docker image prune -a -f
          EOF

      - name: Notify Discord – Deploy Succeeded
        if: success()
        run: |
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}}"
          curl -X POST "$API_URL/$DISCORD_CHANNEL_ID/messages" \
            -H "Authorization: Bot $DISCORD_BOT_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"content\":\"✅ Deploy succeeded for **${{ github.repository }}** (#${{ github.run_number }})\n<$RUN_URL>\"}"

      - name: Notify Discord – Deploy Failed
        if: failure()
        run: |
          LOGS_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/logs}}"
          curl -X POST "$API_URL/$DISCORD_CHANNEL_ID/messages" \
            -H "Authorization: Bot $DISCORD_BOT_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"content\":\"❌ Deploy **failed** for **${{ github.repository }}** (#${{ github.run_number }})\nSee logs: <$LOGS_URL>\"}"

      - name: Install doctl CLI
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/download/v1.101.0/doctl-1.101.0-linux-amd64.tar.gz \
            | tar -xzv doctl && sudo mv doctl /usr/local/bin/

      - name: Authenticate doctl
        run: doctl auth init -t ${{ secrets.DOCR_TOKEN }}

      - name: Prune old registry tags via API
        env:
          DO_API_TOKEN: ${{ secrets.DOCR_TOKEN }}
          REGISTRY_NAME: "sulong-kalinga"
          REPO_NAME: "sulong-kalinga-web"
          KEEP: ${{ github.sha }}
        run: |
          curl -sSL -X GET \
            "https://api.digitalocean.com/v2/registry/${REGISTRY_NAME}/repository/${REPO_NAME}/tags" \
            -H "Authorization: Bearer ${DO_API_TOKEN}" \
          | jq -r '.tags[].name' \
          | grep -v "^${KEEP}$" \
          | xargs -I{} -n1 curl -sSL -X DELETE \
              "https://api.digitalocean.com/v2/registry/${REGISTRY_NAME}/repository/${REPO_NAME}/tag/{}" \
              -H "Authorization: Bearer ${DO_API_TOKEN}"