name: Deploy Test Environment

on:
  workflow_dispatch:
  push:
    branches:
      - test
    paths:
      - 'web/**'

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: test
      image_tag: ${{ github.sha }}
